In [1]:
import pandas as pd
import pyarrow.parquet as pq
import numpy as np

In [2]:
data = pq.read_table('/content/drive/MyDrive/cleaned_taxi_data.parquet')
data = data.to_pandas()

data.describe()


VendorID  passenger_count  trip_distance    RatecodeID  \
count  2.276461e+06     2.276461e+06   2.276461e+06  2.276461e+06   
mean   1.713920e+00     1.472616e+00   2.017087e+00  1.003058e+00   
std    4.519271e-01     1.039033e+00   1.671309e+00  9.978257e-02   
min    1.000000e+00     1.000000e+00   1.000000e-02  1.000000e+00   
25%    1.000000e+00     1.000000e+00   1.020000e+00  1.000000e+00   
50%    2.000000e+00     1.000000e+00   1.610000e+00  1.000000e+00   
75%    2.000000e+00     2.000000e+00   2.520000e+00  1.000000e+00   
max    2.000000e+00     7.000000e+00   9.990000e+01  6.000000e+00   

       store_and_fwd_flag  PULocationID  DOLocationID  payment_type  \
count        2.276461e+06  2.276461e+06  2.276461e+06  2.276461e+06   
mean         7.788844e-03  1.682210e+02  1.668505e+02  1.224111e+00   
std          8.791008e-02  6.633780e+01  6.843555e+01  4.314849e-01   
min          0.000000e+00  4.000000e+00  4.000000e+00  1.000000e+00   
25%          0.000000e+00  1.250000e+02  1.140000e+02  1.000000e+00   
50%          0.000000e+00  1.630000e+02  1.630000e+02  1.000000e+00   
75%          0.000000e+00  2.360000e+02  2.360000e+02  1.000000e+00   
max          1.000000e+00  2.630000e+02  2.630000e+02  4.000000e+00   

        fare_amount         extra  ...   PU_time_min  DO_day_in_june_2021  \
count  2.276461e+06  2.276461e+06  ...  2.276461e+06         2.276461e+06   
mean   9.898870e+00  1.023657e+00  ...  2.964435e+01         1.562462e+01   
std    5.098086e+00  1.194539e+00  ...  1.733007e+01         8.649838e+00   
min    0.000000e+00  0.000000e+00  ...  0.000000e+00         1.000000e+00   
25%    6.500000e+00  0.000000e+00  ...  1.500000e+01         8.000000e+00   
50%    8.500000e+00  5.000000e-01  ...  3.000000e+01         1.600000e+01   
75%    1.200000e+01  2.500000e+00  ...  4.500000e+01         2.300000e+01   
max    3.000000e+02  4.550000e+01  ...  5.900000e+01         3.100000e+01   

       DO_time_hour   DO_time_min      avg_temp    avg_dew_pt  avg_humidity  \
count  2.276461e+06  2.276461e+06  2.276461e+06  2.276461e+06  2.276461e+06   
mean   1.436345e+01  2.960596e+01  7.492776e+01  5.842747e+01  5.911936e+01   
std    5.337169e+00  1.743247e+01  7.183517e+00  8.385969e+00  1.255664e+01   
min    0.000000e+00  0.000000e+00  6.480000e+01  3.780000e+01  3.030000e+01   
25%    1.100000e+01  1.400000e+01  6.860000e+01  5.250000e+01  5.130000e+01   
50%    1.500000e+01  3.000000e+01  7.290000e+01  5.980000e+01  5.760000e+01   
75%    1.800000e+01  4.500000e+01  8.120000e+01  6.710000e+01  6.910000e+01   
max    2.300000e+01  5.900000e+01  8.970000e+01  6.870000e+01  8.390000e+01   

       avg_wind_speed  avg_pressure  total_precipitation  
count    2.276461e+06  2.276461e+06         2.276461e+06  
mean     9.277435e+00  2.997130e+01         6.417241e-02  
std      1.977477e+00  1.711145e-01         1.562487e-01  
min      5.100000e+00  2.970000e+01         0.000000e+00  
25%      8.000000e+00  2.990000e+01         0.000000e+00  
50%      9.500000e+00  2.990000e+01         0.000000e+00  
75%      1.070000e+01  3.010000e+01         0.000000e+00  
max      1.290000e+01  3.030000e+01         6.700000e-01  

[8 rows x 31 columns]

In [3]:
data.columns
# tip_bin is our target variable
# need to drop tip_pct, tip_amount

Index(['VendorID', 'passenger_count', 'trip_distance', 'RatecodeID',
       'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type',
       'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount', 'congestion_surcharge',
       'airport_fee', 'tip_pct', 'tip_bin', 'PU_day_in_june_2021',
       'PU_time_hour', 'PU_time_min', 'DO_day_in_june_2021', 'DO_time_hour',
       'DO_time_min', 'avg_temp', 'avg_dew_pt', 'avg_humidity',
       'avg_wind_speed', 'avg_pressure', 'total_precipitation'],
      dtype='object')

In [4]:
X = data.drop(['tip_pct', 'tip_amount', 'tip_bin'], axis=1)
y = data['tip_bin']

print('Class labels:', np.unique(y))

Class labels: [0 1 2 3]


In [10]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y)
from sklearn.preprocessing import StandardScaler

#normalize data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
import time
#if we want to we can do multiple variations of logistic regressions ie we can add penalities or change the solver
t0=time.time()
model = LogisticRegression(multi_class='multinomial', max_iter = 2000)
model.fit(X_train, y_train)
print("Training time:", time.time()-t0)


Training time: 493.8243534564972


In [15]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#using accuracy confusion matrix to evaluate model
#again can add other metrics if we want

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

confusionmatrix = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{confusionmatrix}")

Accuracy: 0.9678785367360775
Confusion Matrix:
[[229448   1309      5      0]
 [  3012 394869   3099      0]
 [     2  14415  36361     14]
 [     0      0     81    324]]
